apiVersion: apps/v1
kind: Development
metadata:
  name: tristin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tristin-api
  template:
    metadata:
      labels:
        app: tristin-api
  spec:
    containers:
      - name: tristin-api
          image: us-docker.pkg.dev/my-devops-team-404512/tristin-api/api-tests
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10
